### ISSUE TITLE
Program crashes when last element is 0

### ISSUE THREAD

**Issue by s3pt3mb3r** [ToruNiina/toml11#128] opened 2020-09-13 20:43 UTC
I found a bug that causes crash when the last element of toml is 0.

i wrote a code to read from toml file.
```cpp
void Read(const std::string& filename) {
    auto data = toml::parse(filename);
    auto tests = toml::find<std::vector<toml::table>>(config, "test");
    for (toml::table& test : tests) {
        std::cout << test["name"] << std::endl;
    }
}
```

and when the target toml file is like this below, it's gonna work fine.
```toml
[[test]]
name = "note"

[[test]]
name = "pen"
```

but when it comes to this, program crashes.
```toml
[[test]]
name = "note"

[[test]]
name = "pen"
a = 0
```

**Comment by ToruNiina** [comment] 2020-09-14 04:17
Sorry, but I couldn't reproduce the error.
I did the following (on OS X with appleclang), and it works fine.
Could you provide more information, such as compiler, OS, the version of the library, and what error message did you get?

P.S. your code tries to find `tests` from `config`, but not `data`. Is this a typo?

```console
$ cat issue128.cpp
#include "toml.hpp"
#include <iostream>

int main()
{
    auto data = toml::parse("issue128.toml");
    auto tests = toml::find<std::vector<toml::table>>(data, "test");
    for(auto& test : tests)
    {
        std::cout << test["name"] << std::endl;
    }
    return 0;
}
$ cat issue128.toml
[[test]]
name = "note"
[[test]]
name = "pen"
a = 0
$ g++ -std=c++11 issue128.cpp
$ ./a.out
"note"
"pen"
```

**Comment by s3pt3mb3r** [comment] 2020-09-14 04:24
Appreciate your quick reply.
Here is my environment:
- **OS** Windows10
- **Compiler** Visual studio 2019
- **IDE** CLion2020

This is the image of the error I got.
![image](https://user-images.githubusercontent.com/33578715/93043573-d05b9400-f684-11ea-883f-277de7f52443.png)

I'm not familiar to the C++ yet, but it's not looks like ordinary error anyway. Idk what sort of things that is, but when I try to `toml::find` a element that doesn'exist in the target file, the completely same error happens.

**Comment by ToruNiina** [comment] 2020-09-14 05:10
Hmm.. it is weird. `toml::find` throws `std::out_of_range` exception when it cannot find the element. Didn't you see any output on your console, like the following?

```console
terminating with uncaught exception of type std::out_of_range: [error] key "foo" not found
 --> issue128.toml
   |
 1 | [[test]]
   | ~~~~~~~~ in this table
```

It is hard to believe to me, but it might be tricky to show an exception thrown (at least in case of `toml::find`. I'm not sure for the current case because I have not figured out the problem yet). Since I have not used the IDE before, I may misunderstand something.
You can try to catch exception explicitly to show the error message if you want.

```cpp
try {
  // ...
}
catch (std::exception& e) {
    std::cerr << e.what() << std::endl;
}
```

And to show prettier error messages, I recommend not to convert `value` into `table`. Since `table` is an alias of a hash map in the standard library, it does not have toml-specific information. I also recommend to use `at` method instead of operator `[]` because `[]` creates an empty value if the element does not exist in the value. It is useful when you want to construct a `toml::value` but it makes difficult to understand what is happening.

```cpp
    const auto data = toml::parse(filename);
    for (const auto& test : data.at("tests").as_array()) {
        std::cout << test.at("name") << std::endl;
    }
```

I will try to reproduce the error, but since I don't have any windows machine, it will take time. If it is not a problem, could you paste the config file you used to reproduce the error here? I want to check if a special character causes this.

**Comment by s3pt3mb3r** [comment] 2020-09-14 05:28
Alritght, I'll test if I can get any error from it once i get back to home. And also see whether same happens if I use Visual Studio IDE
I'll get back to you.

> P.S. your code tries to find tests from config, but not data. Is this a typo?

This is completely typo. Its because i encountered the error when i was coding my project and I modify the code and sent u.
However, I checked that tbe code I sent is also occurrs the error too.

> could you paste the config file you used to reproduce the error here?
I can but since it's just a simple toml file, there's nothing to do with it.

> I also recommend to use at method instead of operator []

Thank you so much for the tips. Honestly I was in need of these！

**Comment by s3pt3mb3r** [comment] 2020-09-14 06:17
This is the result when I did `try` `catch` to get error explicitly.
```
[error] toml::parse_table: invalid line format
 --> test.toml
   |
 6 | a = 0
   |     ^- expected newline, but got '0'.
```

Additionally, I also have done this with Visual Studio 2019. It acts completely same as CLion IDE. It showed me a modal, and the error I pasted above when I put `try` `catch`. SAME.

**Comment by ToruNiina** [comment] 2020-09-14 06:45
Thank you for the additional information!

I ran the code I pasted above on windows, and still I couldn't reproduce. It works fine with MSVC 19.27.29111.0 and C++17.
https://github.com/ToruNiina/sandbox/runs/1110629089?check_suite_focus=true

It seems that there could be some special character or something like that. Could you upload the file here or show me the hexdump if it is not a problem?

**Comment by s3pt3mb3r** [comment] 2020-09-14 07:04
> still I couldn't reproduce.

really... I'm so sad to hear it.

> Could you upload the file here or show me the hexdump if it is not a problem?

I dont understand what u mean by hexdump.
but anyway I attach the test.toml file here. Github doesnt support toml file, so I changed the extension. It is same as what I told you tho.

[test.txt](https://github.com/ToruNiina/toml11/files/5216565/test.txt)

**Comment by ToruNiina** [comment] 2020-09-14 07:08
Thank you for uploading it. But it seems that it does not have the problematic line, `a = 0`...

**Comment by s3pt3mb3r** [comment] 2020-09-14 07:09
I'm so so so so sorry!!!!!!
Here you go!
[test.txt](https://github.com/ToruNiina/toml11/files/5216657/test.txt)

**Comment by s3pt3mb3r** [comment] 2020-09-14 07:29
Also, this is my main.cpp. If you find it helpful
[main.txt](https://github.com/ToruNiina/toml11/files/5216770/main.txt)

**Comment by ToruNiina** [comment] 2020-09-14 07:37
Now I could reproduce it. I found a bug that happens only when the last character of the file is not `\n` and the last value is `0`. I think I fixed it (now I'm waiting CI). Thank you for finding this case and kind cooperation for telling me what is happening!

**Comment by s3pt3mb3r** [comment] 2020-09-14 07:41
> I think I fixed it

I'm really glad to hear that!!

> Thank you for finding this case and kind cooperation for telling me what is happening!

You're welcome! Thank you for reacting to this issue so quickly every time too.

**Comment by ToruNiina** [comment] 2020-09-14 08:15
I merged the fix and the test case. It hopefully fix the problem on your code. Thank you very much again!

**Closed by ToruNiina** 2020-09-14 08:15 UTC
