### ISSUE TITLE
Hard to use in vcpkg

### ISSUE THREAD

**Issue by ncihnegn** [ToruNiina/toml11#110] opened 2020-03-29 05:14 UTC
```vcpkg_fixup_cmake_targets(CONFIG_PATH share/toml11)``` is not enough.
toml11config.cmake still looks for ```lib/cmake/toml11```.
Perhaps we can avoid hard-coded paths in CMakeLists.txt.

**Comment by ToruNiina** [comment] 2020-03-29 14:12
Unfortunately, I don't have any experience or knowledge in vcpkg. Therefore I have no idea about the usage of it in your situation. So I want to ask for more details about the problem.

I thought that vcpkg is for Windows only, but I just found out that it works also for linux and OS X. Since I have just installed it on VM, I can reproduce your problem if you provide the way to do that.

> Perhaps we can avoid hard-coded paths in CMakeLists.txt.

Do you have any idea about which one should be changed?

FYI, the location where toml11 will be installed can be changed via `CMAKE_INSTALL_LIBDIR`, `CMAKE_INSTALL_INCLUDEDIR` and `CMAKE_INSTALL_PREFIX`.

**Comment by ncihnegn** [comment] 2020-03-30 04:31
I will take a shot at this. I was thinking of a github action to test vcpkg integration, but it seems out of the scope for this project.

**Comment by Neumann-A** [comment] 2021-09-11 22:16
The problem is:
https://github.com/ToruNiina/toml11/blob/fda0a2b9abd16e356f777c40a675131821c71b00/cmake/toml11Config.cmake.in#L2
It should just state 
`include("${CMAKE_CURRENT_LIST_DIR}/toml11Targets.cmake")`
since targets and configs should reside in the same directory.

**Comment by ToruNiina** [comment] 2024-06-14 15:17
merged the pull request that includes the change suggested here.

**Closed by ToruNiina** 2024-06-14 15:17 UTC
