### ISSUE TITLE
Duplicated comments of first table in an array of tables

### ISSUE THREAD

**Issue by TutorExilius** [ToruNiina/toml11#131] opened 2020-09-20 16:16 UTC
I got problems with array of tables.

Comments of first table into the array will be duplicated.

Here, in case of an array of tables, each table will serialise its own comments. This is done by on of these lines:
https://github.com/ToruNiina/toml11/blob/c037913b2c9385f70430a74381b1684a199a5e96/toml/serializer.hpp#L277-L285
https://github.com/ToruNiina/toml11/blob/c037913b2c9385f70430a74381b1684a199a5e96/toml/serializer.hpp#L309-L317

But, after that happened, following lines will duplicate the comment of my first table:
https://github.com/ToruNiina/toml11/blob/c037913b2c9385f70430a74381b1684a199a5e96/toml/serializer.hpp#L654-L662

Example:

Inputfile:
```toml
# comment 1
[[foo]]
# comment 2
[[foo]]
# comment 3
[[foo]]
```

Outputfile:
```toml
# comment 1
# comment 1
[[foo]]
# comment 2
[[foo]]
# comment 3
[[foo]]
```

(thanks slarti)

**Comment by ToruNiina** [comment] 2020-09-20 17:12
Thank you for telling me the problem! I reproduced it. It is a bug. And the reason is as you pointed out.

A quick solution might be to check the first character of the `tmp` in the line 654. Checking types of the first element might fail to solve this in the case of heterogeneous arrays of which first element is an inline table.

The code for comments was added later than the serializer itself, so it's not very clean...
The best solution is refactoring, but it might take some time.

**Comment by TutorExilius** [comment] 2020-09-21 07:33
Thank you. I Hope you will be able to fix it soon :).
I was looking for a TOML Library and found that one, great job!

**Comment by ToruNiina** [comment] 2020-09-22 09:36
Although I will further refactor the code related to the comments, but I have added a first aid for this problem. I hope it will resolve the problem.

**Comment by voldemur** [comment] 2020-10-09 16:15
@ToruNiina, Fix works only for empty first table. If table is not empty then comment is dublicated inside of the table.

input:

```
# comment 1
[[Test_table]]
abracadabra = 10
```
output:
```
# comment 1
Test_table = [
# comment 1
{abracadabra=10}
]
```

**Comment by ToruNiina** [comment] 2020-10-09 17:19
Thank you for reporting it!

On the last saturday I found the core part of the problem reported here (still not fixed yet, though). Essentially, [[test_table]] defines an array that contains tables and a table that is the first element of the array at the same time. A comment on top of [[test_table]] is considered as a comment of both the array and the table element.

This is why both the array and the first element has the same comment in your example. Unfortunately, my patch only workarounds the case if [[]] format is selected. Because of the line width limit, your tables are inlined and my (ad-hoc) workaround does not work.

In order to fix this problem, we must first clarify whether the comment is for an array or an element. In my opinion, it is okay to consider the comment is for the first element in this case. Then I need to change the value initialization part, but this part is a bit tough and I'm now doing this.

Hopefully it will be fixed soon.

**Closed** 2020-10-14 06:35 UTC

**Comment by ToruNiina** [comment] 2020-10-14 06:41
I have just pushed the solution and tests. It seems to be fixed.

Thank you again for reporting the problem!
